// Package platformapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package platformapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "github.com/antoniobt12062002/torcida-jovem-platform/api/internal/platform/apicommon"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuditLogActorType.
const (
	Anonymous AuditLogActorType = "anonymous"
	System    AuditLogActorType = "system"
	User      AuditLogActorType = "user"
)

// Valid indicates whether the value is a known member of the AuditLogActorType enum.
func (e AuditLogActorType) Valid() bool {
	switch e {
	case Anonymous:
		return true
	case System:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for AuditLogOutcome.
const (
	AuditLogOutcomeDenied  AuditLogOutcome = "denied"
	AuditLogOutcomeFailure AuditLogOutcome = "failure"
	AuditLogOutcomeSuccess AuditLogOutcome = "success"
)

// Valid indicates whether the value is a known member of the AuditLogOutcome enum.
func (e AuditLogOutcome) Valid() bool {
	switch e {
	case AuditLogOutcomeDenied:
		return true
	case AuditLogOutcomeFailure:
		return true
	case AuditLogOutcomeSuccess:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Ok       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for GetAuditLogsParamsOutcome.
const (
	GetAuditLogsParamsOutcomeDenied  GetAuditLogsParamsOutcome = "denied"
	GetAuditLogsParamsOutcomeFailure GetAuditLogsParamsOutcome = "failure"
	GetAuditLogsParamsOutcomeSuccess GetAuditLogsParamsOutcome = "success"
)

// Valid indicates whether the value is a known member of the GetAuditLogsParamsOutcome enum.
func (e GetAuditLogsParamsOutcome) Valid() bool {
	switch e {
	case GetAuditLogsParamsOutcomeDenied:
		return true
	case GetAuditLogsParamsOutcomeFailure:
		return true
	case GetAuditLogsParamsOutcomeSuccess:
		return true
	default:
		return false
	}
}

// AuditLog Registro imutável de auditoria.
type AuditLog struct {
	Action      string                  `json:"action"`
	ActorType   AuditLogActorType       `json:"actor_type"`
	ActorUserId *openapi_types.UUID     `json:"actor_user_id"`
	After       *map[string]interface{} `json:"after"`
	Before      *map[string]interface{} `json:"before"`
	Context     map[string]interface{}  `json:"context"`

	// EntityId Identificador do alvo da ação.
	EntityId string `json:"entity_id"`

	// EntityType Tipo do alvo da ação.
	EntityType string             `json:"entity_type"`
	Id         openapi_types.UUID `json:"id"`
	OccurredAt time.Time          `json:"occurred_at"`
	Outcome    AuditLogOutcome    `json:"outcome"`
	Reason     *string            `json:"reason"`
	RequestId  *string            `json:"request_id"`
}

// AuditLogActorType defines model for AuditLog.ActorType.
type AuditLogActorType string

// AuditLogOutcome defines model for AuditLog.Outcome.
type AuditLogOutcome string

// AuditLogPage defines model for AuditLogPage.
type AuditLogPage struct {
	Items []AuditLog `json:"items"`

	// NextCursor Cursor da próxima página, ou null na última.
	NextCursor *string `json:"next_cursor"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// GetAuditLogsParams defines parameters for GetAuditLogs.
type GetAuditLogsParams struct {
	EntityType  *string                    `form:"entity_type,omitempty" json:"entity_type,omitempty"`
	EntityId    *string                    `form:"entity_id,omitempty" json:"entity_id,omitempty"`
	ActorUserId *openapi_types.UUID        `form:"actor_user_id,omitempty" json:"actor_user_id,omitempty"`
	Action      *string                    `form:"action,omitempty" json:"action,omitempty"`
	Outcome     *GetAuditLogsParamsOutcome `form:"outcome,omitempty" json:"outcome,omitempty"`
	From        *time.Time                 `form:"from,omitempty" json:"from,omitempty"`
	To          *time.Time                 `form:"to,omitempty" json:"to,omitempty"`

	// Limit Quantidade de itens por página.
	Limit *externalRef0.Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Cursor da página, vindo de next_cursor.
	Cursor *externalRef0.CursorParam `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetAuditLogsParamsOutcome defines parameters for GetAuditLogs.
type GetAuditLogsParamsOutcome string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetAuditLogs Consulta o registro de auditoria, do mais novo para o mais antigo.
	// (GET /api/v1/audit-logs)
	GetAuditLogs(c *gin.Context, params GetAuditLogsParams)
	// GetHealth Estado da API e do banco de dados.
	// (GET /healthz)
	GetHealth(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAuditLogs operation middleware
func (siw *ServerInterfaceWrapper) GetAuditLogs(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuditLogsParams

	// ------------- Optional query parameter "entity_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "entity_type", c.Request.URL.Query(), &params.EntityType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter entity_type: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "entity_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "entity_id", c.Request.URL.Query(), &params.EntityId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter entity_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "actor_user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "actor_user_id", c.Request.URL.Query(), &params.ActorUserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter actor_user_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "action" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "action", c.Request.URL.Query(), &params.Action, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter action: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "outcome" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "outcome", c.Request.URL.Query(), &params.Outcome, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter outcome: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuditLogs(c, params)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealth)
	router.GET(options.BaseURL+"/api/v1/audit-logs", wrapper.GetAuditLogs)
}

type GetAuditLogsRequestObject struct {
	Params GetAuditLogsParams
}

type GetAuditLogsResponseObject interface {
	VisitGetAuditLogsResponse(w http.ResponseWriter) error
}

type GetAuditLogs200JSONResponse AuditLogPage

func (response GetAuditLogs200JSONResponse) VisitGetAuditLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuditLogs401ApplicationProblemPlusJSONResponse struct {
	externalRef0.UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetAuditLogs401ApplicationProblemPlusJSONResponse) VisitGetAuditLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuditLogs403ApplicationProblemPlusJSONResponse struct {
	externalRef0.ForbiddenApplicationProblemPlusJSONResponse
}

func (response GetAuditLogs403ApplicationProblemPlusJSONResponse) VisitGetAuditLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuditLogs422ApplicationProblemPlusJSONResponse struct {
	externalRef0.ValidationFailedApplicationProblemPlusJSONResponse
}

func (response GetAuditLogs422ApplicationProblemPlusJSONResponse) VisitGetAuditLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuditLogs500ApplicationProblemPlusJSONResponse struct {
	externalRef0.InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetAuditLogs500ApplicationProblemPlusJSONResponse) VisitGetAuditLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuditLogs503ApplicationProblemPlusJSONResponse struct {
	externalRef0.ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response GetAuditLogs503ApplicationProblemPlusJSONResponse) VisitGetAuditLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse Health

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetAuditLogs Consulta o registro de auditoria, do mais novo para o mais antigo.
	// (GET /api/v1/audit-logs)
	GetAuditLogs(ctx context.Context, request GetAuditLogsRequestObject) (GetAuditLogsResponseObject, error)
	// GetHealth Estado da API e do banco de dados.
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetAuditLogs operation middleware
func (sh *strictHandler) GetAuditLogs(ctx *gin.Context, params GetAuditLogsParams) {
	var request GetAuditLogsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuditLogs(ctx, request.(GetAuditLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuditLogs")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetAuditLogsResponseObject); ok {
		if err := validResponse.VisitGetAuditLogsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx *gin.Context) {
	var request GetHealthRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFjNjhu5EX4VgsnBRnok+Q/BKqfNrJ1MskAm9joIMDsQSs1ST9lNsk2yhRkP9DDGHowEyMnIxdd+saDY",
	"f2qpNT/OAnOT2GTxY/Grqq94LVOrC2vQBC/n17IABxoDuvgvtVpbszgunbfulD/xqEKfOioCWSPnsv4o",
	"FIii+pSRgUSsySgrFAqDl2GRxgkTmUji+R9KdFcykQY0yrmsv8pE+vQCNbD93zpcybn8zbSHNq2/+ukA",
	"kdxskhbjj6Qp7KP7ewkmkAKFjIcCGi8K61qsh1Dl0do2KIUrKPMg5y9midRwSbrUcv5kxv/INP8SGa4K",
	"Xk8mYIYMcJNIh76wxuO2S19ZtySl0NRjJqCJ6KEockqB0U8LZ5c56t+98zZOu5eHTuvFNYKhT96gFgU6",
	"Td5Xv9hE2FIcv3n9SqCwjjLUgsy6+pSTsn4iew+fmIDOQP7SOeseADbvKyiCsOJRavk+G0gLZEyPt9G+",
	"QbemFN8aWAPlsMzxASD/gAUaVf3bpASCjCImQvWfNebNAXyNclH2MAeneGugDBfW0UdUD8QUj5EmoqYE",
	"bKP7B/AIz30FlD8IwmPQhfVbjG0cu+6gLVYRWyJSq0XkiWcXb9rgjlH5fako/Giz/QTyGjPygZmny1B9",
	"4qtTKIDnW0cxgRTOFugC1QEOab3yus0FPjgyGbsN0mDdoh6+lmg4Z5zJ0mPMf1c+oJaJBGPNlball+fJ",
	"IRu8ZkHR4SvrNAQ5l2VJijNYmTd0D67EMQurgDF+QSlirJCfbp2gXnXAil2+wzSwlSWurMP/20yky2W4",
	"zc7eOjSBwlXjguGNnSj+uKIUFNclKyBfW65PUH2ufrF8Y3s+acy1VzM0+BMV9o52xq9kb5pN09I5VAsI",
	"g/kKAh4F0ji6qAyp1QPq+DJN0XvJUWEIeS9me+lwlDsOoQm/W0ni8EOJPjQOvmV6M58cp4AzGc+8fcQB",
	"83cpnLQRM7yF7Svu2NaSt3dGd6ieSgPw5yPcaYP9FLLozWH8UkA9/HFThuoSx6bbCJyDK/6/pX5ulE2u",
	"+nJJeks/2VKwx4UBUX3NA+mYZu55CRH9EMSYM/6MkIeLfTf4AKH022Sz7yPPMgcK1Qi/dgA0Bs5Hg35b",
	"xB1yjS0gjSqyAHZLDLpEKFzbfE3KCtS7+nKPxa3YIsxVJ1uG5+RqEU95Cbpg5/aHGDG4YkvD6aCUQ+8n",
	"H6mQt/mkXp7Um97gmbbg7bkmaiBjRZ0xrDhUYsWj16+OxXfPX/z+8X6Fao+84/Xqi6LMCvRtmbOxXCaC",
	"ewJhRZoTmoAiOAgQ/d07ATVQvgjwHs2Y2xQGoHy0JtYVefyktVRPucQnonDo4/6oRVTUPoAXXanvcvKd",
	"wnafGCPxO8yBNxYZEPGaPTUspayEXIAVKSyx+gz5hRX/PHpdGzw6UaNs3Qq51rHPZ9/t9xSJDBTyHdYe",
	"W7PKKQ1jhjvF0ZN2acswX+Zg3t9K2iYd13t2KLtLbdh8S9bl42FaOgpXb/gOBs0QS0yy5tja9zTGzDgu",
	"olyutShqCpwCjBW5zch0bVxam+j6uPCuNd4fEwr6K8YL3tt3lDJD2NNRzFGZklnZMfSGIyZmstTq0lBa",
	"k5UDzFRf0xwtfyjABcovQFnxqMghcIg/nogf2Biu8WeTgiZzYX0i0H8omcaCPZKVDkz1Gf4gDBvlKlj9",
	"i0Mkc3V8GMyqLynZyc+mu8a5/Okv4rTZRRwJXX1RZW5Fu7FM5Bqdr0/wZDKbzKICKdBAQXIun01mk2ec",
	"WCBcxJucQkHT9ZNpFMZHuc3iaIYjLfnLS8pQwFYLyihzpFA6iPqqFdfi0RpdHWTAd52Cj3NLb2Na46QW",
	"c9+JknP5JwxtNfYRWv+ScXY92uUP9UbfkuzFw43Lo0C59+JdEdQbuEU93mCwpvm9ofRaql/6TQrz0AYr",
	"Z/X4EW8QvIeMBftNpsZCu6fIdPCKdPf52y9jm/Odp56ns9kNHfH9OuGBZh3pg9/2+pEjxDVdq6/b3mC5",
	"M7ZerCjnUR5ckgHVlNiXsat/PntyCEZ3runYw0Rc++zOa/u3L1749OmdF+69N2wS+aJ28p3WD1+w4uK7",
	"ox55UIpVrdQa3FWd6H2ZB5ZKrfsHTwUJJ3wN5IWxa9uqqjgAJlBWd5TAmfNMdon4nDeZXkSV/nErp+7l",
	"vkbIfxMHO2HQ636W+5u7vso2e4/w8vvTE4FiCYalfPf8RfXDYuP+bwDXtSG/AsQ/1uBQqBgPg2e6yUC5",
	"yPnZ+faNv/SBy7UCUR9T2fakjbFDNzq0eb0rRM7OOZd4dOu2epUul3M5jTmmMbhbVv/GhKg+V/9Ff1BZ",
	"TPo02sHZnG/+FwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "common.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
