/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/estoque/produtos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todos os produtos (SKUs) de estoque (sem paginação). */
        get: operations["listProdutos"];
        put?: never;
        /** Cria um produto (SKU) de estoque. */
        post: operations["createProduto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estoque/produtos/{id}/movimentacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todas as movimentações do produto, na ordem em que ocorreram (todos os tipos, sem paginação). */
        get: operations["listMovimentacoes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estoque/produtos/{id}/saldo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta o saldo atual do produto (soma de todas as movimentações, zero e negativo incluídos). */
        get: operations["getSaldo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estoque/movimentacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra uma entrada, saída ou devolução de estoque (nunca ajuste — endpoint próprio). */
        post: operations["createMovimentacao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estoque/ajustes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra um ajuste de estoque, com motivo obrigatório — pode levar o saldo a negativo. */
        post: operations["createAjuste"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description O tipo de uma movimentação já registrada — inclui AJUSTE, que só chega aqui através de /api/v1/estoque/ajustes.
         * @enum {string}
         */
        TipoMovimentacao: "ENTRADA" | "SAIDA" | "AJUSTE" | "DEVOLUCAO";
        /** @enum {string} */
        OrigemMovimentacao: "VENDA" | "COMPRA" | "EVENTO" | "INVENTARIO" | "AJUSTE_MANUAL";
        Produto: {
            /** Format: uuid */
            id: string;
            codigo: string;
            nome: string;
            unidade_medida: string;
            /** Format: date-time */
            criado_em: string;
        };
        ProdutoList: {
            items: components["schemas"]["Produto"][];
        };
        CreateProdutoRequest: {
            codigo: string;
            nome: string;
            unidade_medida: string;
        };
        Movimentacao: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            produto_id: string;
            tipo: components["schemas"]["TipoMovimentacao"];
            /**
             * Format: int64
             * @description Já assinado pela aplicação (positivo ou negativo, nunca zero) — soma direta compõe o saldo.
             */
            quantidade: number;
            origem: components["schemas"]["OrigemMovimentacao"];
            /** @description Preenchido só quando tipo=AJUSTE. */
            motivo: string | null;
            /**
             * Format: uuid
             * @description Preenchido só quando tipo=DEVOLUCAO.
             */
            movimentacao_de_id: string | null;
            /** Format: uuid */
            responsavel_id: string;
            /** Format: date-time */
            criado_em: string;
        };
        MovimentacaoList: {
            items: components["schemas"]["Movimentacao"][];
        };
        CreateMovimentacaoRequest: {
            /**
             * @description Nunca AJUSTE aqui — use /api/v1/estoque/ajustes.
             * @enum {string}
             */
            tipo: "ENTRADA" | "SAIDA" | "DEVOLUCAO";
            /** Format: uuid */
            produto_id: string;
            /**
             * Format: int64
             * @description Sempre um inteiro positivo — o sinal é calculado internamente a partir de tipo.
             */
            quantidade: number;
            origem: components["schemas"]["OrigemMovimentacao"];
            /**
             * Format: uuid
             * @description Obrigatório quando tipo=DEVOLUCAO (validado no caso de uso, nunca aqui — devolucao_invalida quando ausente).
             */
            movimentacao_de_id?: string;
        };
        CreateAjusteRequest: {
            /** Format: uuid */
            produto_id: string;
            /**
             * Format: int64
             * @description Delta assinado, nunca zero — pode ser negativo, inclusive levando o saldo a negativo.
             */
            quantidade: number;
            motivo: string;
        };
        Saldo: {
            /** Format: int64 */
            saldo: number;
        };
        FieldError: {
            /** @example address.zip */
            field: string;
            /** @example required */
            code: string;
        };
        /** @description Erro no formato application/problem+json (RFC 9457). */
        Problem: {
            /** @example about:blank */
            type: string;
            /** @example Conflict */
            title: string;
            /** @example 409 */
            status: number;
            detail: string;
            /**
             * @description Código estável do erro, para o cliente tratar.
             * @example email_taken
             */
            code: string;
            /** @description Identificador da requisição, igual ao cabeçalho X-Request-Id. */
            request_id: string;
            /** @description Erros por campo, presente em respostas de validação. */
            errors?: components["schemas"]["FieldError"][];
        };
    };
    responses: {
        /** @description Sem sessão válida. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Sem permissão, ou CSRF e origem inválidos. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Erro interno (code internal_error). */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Dependência indisponível (code service_unavailable). */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Corpo da requisição não é um JSON válido (code invalid_json). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Corpo acima do limite. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Campos inválidos (code validation_failed, com errors). */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Recurso não encontrado (code not_found). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ProdutoId: string;
        /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
        CsrfToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProdutos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todos os produtos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProdutoList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createProduto: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProdutoRequest"];
            };
        };
        responses: {
            /** @description Produto criado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Produto"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Código já utilizado por outro produto (code codigo_duplicado). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listMovimentacoes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProdutoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todas as movimentações do produto. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovimentacaoList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getSaldo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProdutoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saldo atual do produto. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Saldo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createMovimentacao: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMovimentacaoRequest"];
            };
        };
        responses: {
            /** @description Movimentação registrada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Movimentacao"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Produto não encontrado (code produto_nao_encontrado). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Saída (ou devolução de entrada) resultaria em saldo negativo (code saldo_insuficiente). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            /** @description Quantidade inválida ou devolução inválida (quantidade_invalida, devolucao_invalida). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createAjuste: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAjusteRequest"];
            };
        };
        responses: {
            /** @description Ajuste registrado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Movimentacao"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Produto não encontrado (code produto_nao_encontrado). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            /** @description Quantidade inválida ou motivo ausente (quantidade_invalida, motivo_obrigatorio). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
