/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/financeiro/contas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todas as contas contábeis (sem paginação, FIN-D-021). */
        get: operations["listContas"];
        put?: never;
        /** Cria uma conta contábil, raiz ou subconta. */
        post: operations["createConta"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/financeiro/contas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Renomeia uma conta, só enquanto nunca tiver sido usada em um lançamento. */
        patch: operations["renameConta"];
        trace?: never;
    };
    "/api/v1/financeiro/contas/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Desativa uma conta contábil (nunca excluída). */
        post: operations["deactivateConta"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/financeiro/lancamentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todos os lançamentos, incluindo CANCELADA (sem paginação, FIN-D-021). */
        get: operations["listLancamentos"];
        put?: never;
        /** Cria um lançamento (receita ou despesa). */
        post: operations["createLancamento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/financeiro/lancamentos/devolucoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cria uma despesa de devolução, referenciando a receita recebida que devolve (FIN-D-003). */
        post: operations["createDevolucao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/financeiro/lancamentos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Substitui os campos editáveis do lançamento, só enquanto CRIADA. */
        put: operations["updateLancamento"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/financeiro/lancamentos/{id}/receive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transiciona uma receita CRIADA para RECEBIDA. */
        post: operations["receiveLancamento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/financeiro/lancamentos/{id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transiciona uma despesa CRIADA para PAGA. */
        post: operations["payLancamento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/financeiro/lancamentos/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancela um lançamento (CRIADA, RECEBIDA ou PAGA), com motivo obrigatório. */
        post: operations["cancelLancamento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/financeiro/saldo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta o saldo atual (soma RECEBIDA menos soma PAGA por status atual). */
        get: operations["getSaldo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/financeiro/lancamentos/{id}/comprovantes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os comprovantes do lançamento, mais novo primeiro (sem paginação, FIN-D-021). */
        get: operations["listComprovantes"];
        put?: never;
        /** Anexa um comprovante ao lançamento (multipart/form-data, delegado inteiramente a platform/documents). */
        post: operations["createComprovante"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/financeiro/comprovantes/{documentId}/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gera uma URL assinada para baixar o comprovante (delegado inteiramente a platform/documents). */
        get: operations["getComprovanteUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TipoConta: "RECEITA" | "DESPESA";
        /** @enum {string} */
        FormaPagamento: "PIX" | "CARTAO" | "DINHEIRO" | "TRANSFERENCIA" | "OUTROS";
        /** @enum {string} */
        StatusLancamento: "CRIADA" | "RECEBIDA" | "PAGA" | "CANCELADA";
        Conta: {
            /** Format: uuid */
            id: string;
            tipo: components["schemas"]["TipoConta"];
            nome: string;
            /** Format: uuid */
            parent_id: string | null;
            ativo: boolean;
            /** Format: date-time */
            created_at: string;
        };
        ContaList: {
            items: components["schemas"]["Conta"][];
        };
        CreateContaRequest: {
            tipo: components["schemas"]["TipoConta"];
            nome: string;
            /** Format: uuid */
            parent_id?: string | null;
        };
        RenameContaRequest: {
            nome: string;
        };
        Lancamento: {
            /** Format: uuid */
            id: string;
            tipo: components["schemas"]["TipoConta"];
            /** Format: uuid */
            conta_id: string;
            valor_bruto_cents: components["schemas"]["Cents"];
            taxa_cents: components["schemas"]["Cents"];
            valor_liquido_cents: components["schemas"]["Cents"];
            forma_pagamento: components["schemas"]["FormaPagamento"];
            status: components["schemas"]["StatusLancamento"];
            /** Format: uuid */
            devolucao_de_id: string | null;
            motivo_cancelamento: string | null;
            /** Format: uuid */
            cancelado_por: string | null;
            /** Format: date-time */
            cancelado_em: string | null;
            /** Format: uuid */
            criado_por: string;
            /** Format: date-time */
            criado_em: string;
            /** Format: date-time */
            atualizado_em: string;
        };
        LancamentoList: {
            items: components["schemas"]["Lancamento"][];
        };
        CreateLancamentoRequest: {
            tipo: components["schemas"]["TipoConta"];
            /** Format: uuid */
            conta_id: string;
            valor_bruto_cents: components["schemas"]["Cents"];
            taxa_cents: components["schemas"]["Cents"];
            forma_pagamento: components["schemas"]["FormaPagamento"];
        };
        UpdateLancamentoRequest: {
            /** Format: uuid */
            conta_id: string;
            valor_bruto_cents: components["schemas"]["Cents"];
            taxa_cents: components["schemas"]["Cents"];
            forma_pagamento: components["schemas"]["FormaPagamento"];
        };
        CreateDevolucaoRequest: {
            /** Format: uuid */
            conta_id: string;
            valor_bruto_cents: components["schemas"]["Cents"];
            taxa_cents: components["schemas"]["Cents"];
            forma_pagamento: components["schemas"]["FormaPagamento"];
            /** Format: uuid */
            devolucao_de_id: string;
        };
        CancelLancamentoRequest: {
            /** @description Motivo do cancelamento (não pode ser vazio, verificado no caso de uso — API-03 AC4, motivo_obrigatorio). */
            reason: string;
        };
        Saldo: {
            saldo_cents: components["schemas"]["Cents"];
        };
        Comprovante: {
            /** Format: uuid */
            id: string;
            original_filename: string;
            content_type: string;
            /** Format: int64 */
            size_bytes: number;
            version: number;
            /** Format: uuid */
            uploaded_by: string;
            /** Format: date-time */
            uploaded_at: string;
        };
        ComprovanteList: {
            items: components["schemas"]["Comprovante"][];
        };
        ComprovanteUrl: {
            /** Format: uri */
            url: string;
        };
        FieldError: {
            /** @example address.zip */
            field: string;
            /** @example required */
            code: string;
        };
        /** @description Erro no formato application/problem+json (RFC 9457). */
        Problem: {
            /** @example about:blank */
            type: string;
            /** @example Conflict */
            title: string;
            /** @example 409 */
            status: number;
            detail: string;
            /**
             * @description Código estável do erro, para o cliente tratar.
             * @example email_taken
             */
            code: string;
            /** @description Identificador da requisição, igual ao cabeçalho X-Request-Id. */
            request_id: string;
            /** @description Erros por campo, presente em respostas de validação. */
            errors?: components["schemas"]["FieldError"][];
        };
        /**
         * Format: int64
         * @description Valor monetário em centavos de real (10000 equivale a R$ 100,00).
         * @example 12345
         */
        Cents: number;
    };
    responses: {
        /** @description Sem sessão válida. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Sem permissão, ou CSRF e origem inválidos. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Erro interno (code internal_error). */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Dependência indisponível (code service_unavailable). */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Corpo da requisição não é um JSON válido (code invalid_json). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Corpo acima do limite. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Recurso não encontrado (code not_found). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Campos inválidos (code validation_failed, com errors). */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ContaId: string;
        LancamentoId: string;
        DocumentId: string;
        /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
        CsrfToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listContas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todas as contas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContaList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createConta: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContaRequest"];
            };
        };
        responses: {
            /** @description Conta criada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conta"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description parent_id referenciado não existe (code conta_nao_encontrada). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            /** @description Tipo da subconta incompatível com o pai (code conta_tipo_incompativel) ou campos inválidos. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    renameConta: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: components["parameters"]["ContaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameContaRequest"];
            };
        };
        responses: {
            /** @description Conta renomeada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conta"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Conta já utilizada em um lançamento (code conta_ja_utilizada). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    deactivateConta: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: components["parameters"]["ContaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conta desativada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listLancamentos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todos os lançamentos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LancamentoList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createLancamento: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLancamentoRequest"];
            };
        };
        responses: {
            /** @description Lançamento criado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lancamento"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            /** @description Conta inválida, tipo incompatível ou valor fora da faixa segura (conta_invalida, lancamento_tipo_incompativel, amount_out_of_range). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createDevolucao: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDevolucaoRequest"];
            };
        };
        responses: {
            /** @description Devolução criada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lancamento"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            /** @description Conta inválida, devolução inválida (lançamento referenciado não é RECEITA RECEBIDA) ou valor fora da faixa (conta_invalida, devolucao_invalida, amount_out_of_range). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    updateLancamento: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: components["parameters"]["LancamentoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLancamentoRequest"];
            };
        };
        responses: {
            /** @description Lançamento editado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lancamento"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Lançamento fora de CRIADA, não pode mais ser editado (code lancamento_imutavel). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            /** @description Conta inválida, tipo incompatível ou valor fora da faixa (conta_invalida, lancamento_tipo_incompativel, amount_out_of_range). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    receiveLancamento: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: components["parameters"]["LancamentoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lançamento recebido. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Lançamento não pode ser recebido (code lancamento_nao_pode_ser_recebido). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    payLancamento: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: components["parameters"]["LancamentoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lançamento pago. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Lançamento não pode ser pago (code lancamento_nao_pode_ser_pago). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    cancelLancamento: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: components["parameters"]["LancamentoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelLancamentoRequest"];
            };
        };
        responses: {
            /** @description Lançamento cancelado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Lançamento já cancelado (code lancamento_ja_cancelado). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            /** @description Motivo ausente ou vazio (code motivo_obrigatorio). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getSaldo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saldo atual, zero incluído. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Saldo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listComprovantes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LancamentoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todos os comprovantes do lançamento. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComprovanteList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createComprovante: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: components["parameters"]["LancamentoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Comprovante anexado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comprovante"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Lançamento não encontrado (code lancamento_nao_encontrado) — verificado antes de qualquer envio a platform/documents. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Corpo acima do limite da chain de upload (payload_too_large) ou do arquivo em platform/documents (document_too_large). */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Extensão ou tipo de arquivo não permitido (document_extension_not_allowed, document_type_not_allowed, document_type_mismatch). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getComprovanteUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description URL assinada, de validade limitada — nunca cacheada. */
            200: {
                headers: {
                    /** @description Sempre no-store. */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComprovanteUrl"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Comprovante não encontrado (code document_not_found). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
