/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Entra com e-mail e senha e abre uma sessão. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encerra a sessão atual e limpa o cookie. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quem está autenticado, com papéis, permissões efetivas e o token CSRF. */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Troca a própria senha. */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pede a recuperação de acesso por e-mail.
         * @description A resposta é sempre a mesma, exista ou não uma conta vinculada ao e-mail.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Define a nova senha com o token de recuperação. */
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista usuários, do mais novo para o mais antigo, com cursor. */
        get: operations["listUsers"];
        put?: never;
        /** Cria um usuário só com o papel ASSOCIADO e troca de senha obrigatória. */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Desativa o usuário, encerrando suas sessões. */
        post: operations["deactivateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reativa o usuário, sem restaurar papéis administrativos nem vínculo. */
        post: operations["reactivateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Substitui os papéis administrativos de quem já tem vínculo administrativo ativo. */
        put: operations["setUserRoles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/admin-membership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promove o usuário a administrativo (vínculo com motivo mais papéis). */
        post: operations["grantAdminMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/admin-membership/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retira o acesso administrativo, com motivo; o histórico do vínculo é preservado.
         * @description Não é uma exclusão: o vínculo é encerrado e permanece no histórico.
         */
        post: operations["revokeAdminMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redefinição administrativa: gera uma senha temporária, mostrada uma única vez. */
        post: operations["resetUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Papel do sistema. Papéis são agrupadores; a autorização decide por permissões.
         * @enum {string}
         */
        Role: "ASSOCIADO" | "PRESIDENTE" | "DIRETORIA" | "TESOURARIA" | "ESTOQUE_LOJA" | "EVENTOS" | "CONSELHO_FISCAL" | "ADMIN_SISTEMA";
        LoginRequest: {
            email: string;
            password: string;
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        PasswordResetRequest: {
            email: string;
        };
        PasswordResetConfirm: {
            token: string;
            new_password: string;
        };
        Accepted: {
            message: string;
        };
        CreateUserRequest: {
            email: string;
            name: string;
            password: string;
        };
        SetRolesRequest: {
            /** @description Papéis administrativos. ASSOCIADO é sempre mantido; uma lista vazia deixa o vínculo dormente. */
            roles: components["schemas"]["Role"][];
        };
        GrantAdminRequest: {
            /** @description Ao menos um papel administrativo. */
            roles: components["schemas"]["Role"][];
            /** @description Por que a pessoa passa a ter acesso administrativo (mínimo 10 caracteres, verificado no caso de uso). */
            reason: string;
        };
        RevokeAdminRequest: {
            /** @description Por que o acesso administrativo é retirado. */
            reason: string;
        };
        ResetUserPasswordRequest: {
            /** @description Motivo da redefinição (mínimo 10 caracteres, verificado no caso de uso). */
            reason: string;
        };
        TemporaryPassword: {
            /** @description Senha temporária, exibida uma única vez. Nunca é registrada em log nem na auditoria. */
            temporary_password: string;
        };
        UserRef: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
        };
        /** @description Vínculo administrativo ativo, ou null. Não traz o concedente nem o histórico. */
        AdminMembershipSummary: {
            reason: string;
            /** Format: date-time */
            granted_at: string;
        } | null;
        /** @description Contexto da sessão, igual no login e em GET /auth/me. */
        AuthContext: {
            user: components["schemas"]["UserRef"];
            roles: components["schemas"]["Role"][];
            /** @description Permissões efetivas (módulo:recurso:ação). */
            permissions: string[];
            csrf_token: string;
            must_change_password: boolean;
            admin_membership: components["schemas"]["AdminMembershipSummary"];
        };
        User: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
            active: boolean;
            must_change_password: boolean;
            /** Format: date-time */
            created_at: string;
            roles: components["schemas"]["Role"][];
            admin_membership: components["schemas"]["AdminMembershipSummary"];
        };
        UserPage: {
            items: components["schemas"]["User"][];
            /** @description Cursor da próxima página, ou null na última. */
            next_cursor: string | null;
        };
        FieldError: {
            /** @example address.zip */
            field: string;
            /** @example required */
            code: string;
        };
        /** @description Erro no formato application/problem+json (RFC 9457). */
        Problem: {
            /** @example about:blank */
            type: string;
            /** @example Conflict */
            title: string;
            /** @example 409 */
            status: number;
            detail: string;
            /**
             * @description Código estável do erro, para o cliente tratar.
             * @example email_taken
             */
            code: string;
            /** @description Identificador da requisição, igual ao cabeçalho X-Request-Id. */
            request_id: string;
            /** @description Erros por campo, presente em respostas de validação. */
            errors?: components["schemas"]["FieldError"][];
        };
        /** @description Cursor opaco de paginação, devolvido em next_cursor. */
        Cursor: string;
    };
    responses: {
        /** @description Corpo da requisição não é um JSON válido (code invalid_json). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Sem permissão, ou CSRF e origem inválidos. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Corpo acima do limite. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Campos inválidos (code validation_failed, com errors). */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Tentativas em excesso; o cabeçalho Retry-After diz em quantos segundos tentar de novo. */
        TooManyRequests: {
            headers: {
                /** @description Segundos até a próxima tentativa. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Erro interno (code internal_error). */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Sem sessão válida. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Conflito com o estado atual (por exemplo email_taken ou last_admin). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Recurso não encontrado (code not_found). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        UserId: string;
        /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
        CsrfToken: string;
        /** @description Quantidade de itens por página. */
        Limit: number;
        /** @description Cursor da página, vindo de next_cursor. */
        CursorParam: components["schemas"]["Cursor"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Sessão aberta. O cookie tj_session é emitido, e o corpo é o mesmo de GET /auth/me. */
            200: {
                headers: {
                    /** @description Cookie de sessão tj_session (HttpOnly, Secure, SameSite=Lax, Path=/). */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthContext"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Credenciais inválidas (code invalid_credentials), sempre com a mesma resposta. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessão encerrada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contexto da sessão atual. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthContext"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Senha trocada; as outras sessões foram encerradas. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Pedido recebido. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Se existir uma conta vinculada ao e-mail informado, enviaremos instruções."
                     *     }
                     */
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Senha redefinida; todas as sessões do usuário foram encerradas. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON inválido (invalid_json) ou token de recuperação desconhecido, expirado ou usado (invalid_reset_token). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                active?: boolean;
                role?: components["schemas"]["Role"];
                /** @description Quantidade de itens por página. */
                limit?: components["parameters"]["Limit"];
                /** @description Cursor da página, vindo de next_cursor. */
                cursor?: components["parameters"]["CursorParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Uma página de usuários. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Usuário criado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    deactivateUser: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário desativado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    reactivateUser: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário reativado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    setUserRoles: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRolesRequest"];
            };
        };
        responses: {
            /** @description Papéis atualizados. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    grantAdminMembership: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantAdminRequest"];
            };
        };
        responses: {
            /** @description Usuário promovido; as sessões dele foram encerradas e a troca de senha passou a ser obrigatória. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    revokeAdminMembership: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeAdminRequest"];
            };
        };
        responses: {
            /** @description Acesso retirado; só o papel ASSOCIADO permanece e as sessões foram encerradas. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
    resetUserPassword: {
        parameters: {
            query?: never;
            header: {
                /** @description Token anti-CSRF da sessão, obrigatório em requisições que alteram estado. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetUserPasswordRequest"];
            };
        };
        responses: {
            /** @description Senha temporária gerada; a resposta não pode ser guardada em cache. */
            200: {
                headers: {
                    /** @description Sempre no-store. */
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemporaryPassword"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
}
