/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado da API e do banco de dados. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consulta o registro de auditoria, do mais novo para o mais antigo.
         * @description Exige a permissão de leitura da auditoria (verificada no caso de uso).
         */
        get: operations["getAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Registro imutável de auditoria. */
        AuditLog: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            occurred_at: string;
            /** @enum {string} */
            actor_type: "user" | "system" | "anonymous";
            /** Format: uuid */
            actor_user_id: string | null;
            action: string;
            /** @description Tipo do alvo da ação. */
            entity_type: string;
            /** @description Identificador do alvo da ação. */
            entity_id: string;
            before: {
                [key: string]: unknown;
            } | null;
            after: {
                [key: string]: unknown;
            } | null;
            /** @enum {string} */
            outcome: "success" | "denied" | "failure";
            reason: string | null;
            context: {
                [key: string]: unknown;
            };
            request_id: string | null;
        };
        AuditLogPage: {
            items: components["schemas"]["AuditLog"][];
            /** @description Cursor da próxima página, ou null na última. */
            next_cursor: string | null;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
        };
        /** @description Cursor opaco de paginação, devolvido em next_cursor. */
        Cursor: string;
        FieldError: {
            /** @example address.zip */
            field: string;
            /** @example required */
            code: string;
        };
        /** @description Erro no formato application/problem+json (RFC 9457). */
        Problem: {
            /** @example about:blank */
            type: string;
            /** @example Conflict */
            title: string;
            /** @example 409 */
            status: number;
            detail: string;
            /**
             * @description Código estável do erro, para o cliente tratar.
             * @example email_taken
             */
            code: string;
            /** @description Identificador da requisição, igual ao cabeçalho X-Request-Id. */
            request_id: string;
            /** @description Erros por campo, presente em respostas de validação. */
            errors?: components["schemas"]["FieldError"][];
        };
    };
    responses: {
        /** @description Sem sessão válida. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Sem permissão, ou CSRF e origem inválidos. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Campos inválidos (code validation_failed, com errors). */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Erro interno (code internal_error). */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Quantidade de itens por página. */
        Limit: number;
        /** @description Cursor da página, vindo de next_cursor. */
        CursorParam: components["schemas"]["Cursor"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API e banco disponíveis. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Banco de dados indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "degraded"
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getAuditLogs: {
        parameters: {
            query?: {
                entity_type?: string;
                entity_id?: string;
                actor_user_id?: string;
                action?: string;
                outcome?: "success" | "denied" | "failure";
                from?: string;
                to?: string;
                /** @description Quantidade de itens por página. */
                limit?: components["parameters"]["Limit"];
                /** @description Cursor da página, vindo de next_cursor. */
                cursor?: components["parameters"]["CursorParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Uma página de registros, com todos os filtros combinados por E. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalError"];
        };
    };
}
