// Package estoquehttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package estoquehttp

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "github.com/antoniobt12062002/torcida-jovem-platform/api/internal/platform/apicommon"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateMovimentacaoRequestTipo.
const (
	CreateMovimentacaoRequestTipoDEVOLUCAO CreateMovimentacaoRequestTipo = "DEVOLUCAO"
	CreateMovimentacaoRequestTipoENTRADA   CreateMovimentacaoRequestTipo = "ENTRADA"
	CreateMovimentacaoRequestTipoSAIDA     CreateMovimentacaoRequestTipo = "SAIDA"
)

// Valid indicates whether the value is a known member of the CreateMovimentacaoRequestTipo enum.
func (e CreateMovimentacaoRequestTipo) Valid() bool {
	switch e {
	case CreateMovimentacaoRequestTipoDEVOLUCAO:
		return true
	case CreateMovimentacaoRequestTipoENTRADA:
		return true
	case CreateMovimentacaoRequestTipoSAIDA:
		return true
	default:
		return false
	}
}

// Defines values for OrigemMovimentacao.
const (
	AJUSTEMANUAL OrigemMovimentacao = "AJUSTE_MANUAL"
	COMPRA       OrigemMovimentacao = "COMPRA"
	EVENTO       OrigemMovimentacao = "EVENTO"
	INVENTARIO   OrigemMovimentacao = "INVENTARIO"
	VENDA        OrigemMovimentacao = "VENDA"
)

// Valid indicates whether the value is a known member of the OrigemMovimentacao enum.
func (e OrigemMovimentacao) Valid() bool {
	switch e {
	case AJUSTEMANUAL:
		return true
	case COMPRA:
		return true
	case EVENTO:
		return true
	case INVENTARIO:
		return true
	case VENDA:
		return true
	default:
		return false
	}
}

// Defines values for TipoMovimentacao.
const (
	TipoMovimentacaoAJUSTE    TipoMovimentacao = "AJUSTE"
	TipoMovimentacaoDEVOLUCAO TipoMovimentacao = "DEVOLUCAO"
	TipoMovimentacaoENTRADA   TipoMovimentacao = "ENTRADA"
	TipoMovimentacaoSAIDA     TipoMovimentacao = "SAIDA"
)

// Valid indicates whether the value is a known member of the TipoMovimentacao enum.
func (e TipoMovimentacao) Valid() bool {
	switch e {
	case TipoMovimentacaoAJUSTE:
		return true
	case TipoMovimentacaoDEVOLUCAO:
		return true
	case TipoMovimentacaoENTRADA:
		return true
	case TipoMovimentacaoSAIDA:
		return true
	default:
		return false
	}
}

// CreateAjusteRequest defines model for CreateAjusteRequest.
type CreateAjusteRequest struct {
	Motivo    string             `json:"motivo"`
	ProdutoId openapi_types.UUID `json:"produto_id"`

	// Quantidade Delta assinado, nunca zero — pode ser negativo, inclusive levando o saldo a negativo.
	Quantidade int64 `json:"quantidade"`
}

// CreateMovimentacaoRequest defines model for CreateMovimentacaoRequest.
type CreateMovimentacaoRequest struct {
	// MovimentacaoDeId Obrigatório quando tipo=DEVOLUCAO (validado no caso de uso, nunca aqui — devolucao_invalida quando ausente).
	MovimentacaoDeId *openapi_types.UUID `json:"movimentacao_de_id,omitempty"`
	Origem           OrigemMovimentacao  `json:"origem"`
	ProdutoId        openapi_types.UUID  `json:"produto_id"`

	// Quantidade Sempre um inteiro positivo — o sinal é calculado internamente a partir de tipo.
	Quantidade int64 `json:"quantidade"`

	// Tipo Nunca AJUSTE aqui — use /api/v1/estoque/ajustes.
	Tipo CreateMovimentacaoRequestTipo `json:"tipo"`
}

// CreateMovimentacaoRequestTipo Nunca AJUSTE aqui — use /api/v1/estoque/ajustes.
type CreateMovimentacaoRequestTipo string

// CreateProdutoRequest defines model for CreateProdutoRequest.
type CreateProdutoRequest struct {
	Codigo        string `json:"codigo"`
	Nome          string `json:"nome"`
	UnidadeMedida string `json:"unidade_medida"`
}

// Movimentacao defines model for Movimentacao.
type Movimentacao struct {
	CriadoEm time.Time          `json:"criado_em"`
	Id       openapi_types.UUID `json:"id"`

	// Motivo Preenchido só quando tipo=AJUSTE.
	Motivo *string `json:"motivo"`

	// MovimentacaoDeId Preenchido só quando tipo=DEVOLUCAO.
	MovimentacaoDeId *openapi_types.UUID `json:"movimentacao_de_id"`
	Origem           OrigemMovimentacao  `json:"origem"`
	ProdutoId        openapi_types.UUID  `json:"produto_id"`

	// Quantidade Já assinado pela aplicação (positivo ou negativo, nunca zero) — soma direta compõe o saldo.
	Quantidade    int64              `json:"quantidade"`
	ResponsavelId openapi_types.UUID `json:"responsavel_id"`

	// Tipo O tipo de uma movimentação já registrada — inclui AJUSTE, que só chega aqui através de /api/v1/estoque/ajustes.
	Tipo TipoMovimentacao `json:"tipo"`
}

// MovimentacaoList defines model for MovimentacaoList.
type MovimentacaoList struct {
	Items []Movimentacao `json:"items"`
}

// OrigemMovimentacao defines model for OrigemMovimentacao.
type OrigemMovimentacao string

// Produto defines model for Produto.
type Produto struct {
	Codigo        string             `json:"codigo"`
	CriadoEm      time.Time          `json:"criado_em"`
	Id            openapi_types.UUID `json:"id"`
	Nome          string             `json:"nome"`
	UnidadeMedida string             `json:"unidade_medida"`
}

// ProdutoList defines model for ProdutoList.
type ProdutoList struct {
	Items []Produto `json:"items"`
}

// Saldo defines model for Saldo.
type Saldo struct {
	Saldo int64 `json:"saldo"`
}

// TipoMovimentacao O tipo de uma movimentação já registrada — inclui AJUSTE, que só chega aqui através de /api/v1/estoque/ajustes.
type TipoMovimentacao string

// ProdutoId defines model for ProdutoId.
type ProdutoId = openapi_types.UUID

// CreateAjusteParams defines parameters for CreateAjuste.
type CreateAjusteParams struct {
	// XCSRFToken Token anti-CSRF da sessão, obrigatório em requisições que alteram estado.
	XCSRFToken externalRef0.CsrfToken `json:"X-CSRF-Token"`
}

// CreateMovimentacaoParams defines parameters for CreateMovimentacao.
type CreateMovimentacaoParams struct {
	// XCSRFToken Token anti-CSRF da sessão, obrigatório em requisições que alteram estado.
	XCSRFToken externalRef0.CsrfToken `json:"X-CSRF-Token"`
}

// CreateProdutoParams defines parameters for CreateProduto.
type CreateProdutoParams struct {
	// XCSRFToken Token anti-CSRF da sessão, obrigatório em requisições que alteram estado.
	XCSRFToken externalRef0.CsrfToken `json:"X-CSRF-Token"`
}

// CreateAjusteJSONRequestBody defines body for CreateAjuste for application/json ContentType.
type CreateAjusteJSONRequestBody = CreateAjusteRequest

// CreateMovimentacaoJSONRequestBody defines body for CreateMovimentacao for application/json ContentType.
type CreateMovimentacaoJSONRequestBody = CreateMovimentacaoRequest

// CreateProdutoJSONRequestBody defines body for CreateProduto for application/json ContentType.
type CreateProdutoJSONRequestBody = CreateProdutoRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateAjuste Registra um ajuste de estoque, com motivo obrigatório — pode levar o saldo a negativo.
	// (POST /api/v1/estoque/ajustes)
	CreateAjuste(c *gin.Context, params CreateAjusteParams)
	// CreateMovimentacao Registra uma entrada, saída ou devolução de estoque (nunca ajuste — endpoint próprio).
	// (POST /api/v1/estoque/movimentacoes)
	CreateMovimentacao(c *gin.Context, params CreateMovimentacaoParams)
	// ListProdutos Lista todos os produtos (SKUs) de estoque (sem paginação).
	// (GET /api/v1/estoque/produtos)
	ListProdutos(c *gin.Context)
	// CreateProduto Cria um produto (SKU) de estoque.
	// (POST /api/v1/estoque/produtos)
	CreateProduto(c *gin.Context, params CreateProdutoParams)
	// ListMovimentacoes Lista todas as movimentações do produto, na ordem em que ocorreram (todos os tipos, sem paginação).
	// (GET /api/v1/estoque/produtos/{id}/movimentacoes)
	ListMovimentacoes(c *gin.Context, id ProdutoId)
	// GetSaldo Consulta o saldo atual do produto (soma de todas as movimentações, zero e negativo incluídos).
	// (GET /api/v1/estoque/produtos/{id}/saldo)
	GetSaldo(c *gin.Context, id ProdutoId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateAjuste operation middleware
func (siw *ServerInterfaceWrapper) CreateAjuste(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateAjusteParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken externalRef0.CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAjuste(c, params)
}

// CreateMovimentacao operation middleware
func (siw *ServerInterfaceWrapper) CreateMovimentacao(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateMovimentacaoParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken externalRef0.CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateMovimentacao(c, params)
}

// ListProdutos operation middleware
func (siw *ServerInterfaceWrapper) ListProdutos(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListProdutos(c)
}

// CreateProduto operation middleware
func (siw *ServerInterfaceWrapper) CreateProduto(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateProdutoParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken externalRef0.CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateProduto(c, params)
}

// ListMovimentacoes operation middleware
func (siw *ServerInterfaceWrapper) ListMovimentacoes(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ProdutoId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMovimentacoes(c, id)
}

// GetSaldo operation middleware
func (siw *ServerInterfaceWrapper) GetSaldo(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ProdutoId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSaldo(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/estoque/produtos", wrapper.ListProdutos)
	router.POST(options.BaseURL+"/api/v1/estoque/produtos", wrapper.CreateProduto)
	router.GET(options.BaseURL+"/api/v1/estoque/produtos/:id/movimentacoes", wrapper.ListMovimentacoes)
	router.GET(options.BaseURL+"/api/v1/estoque/produtos/:id/saldo", wrapper.GetSaldo)
	router.POST(options.BaseURL+"/api/v1/estoque/movimentacoes", wrapper.CreateMovimentacao)
	router.POST(options.BaseURL+"/api/v1/estoque/ajustes", wrapper.CreateAjuste)
}

type CreateAjusteRequestObject struct {
	Params CreateAjusteParams
	Body   *CreateAjusteJSONRequestBody
}

type CreateAjusteResponseObject interface {
	VisitCreateAjusteResponse(w http.ResponseWriter) error
}

type CreateAjuste201JSONResponse Movimentacao

func (response CreateAjuste201JSONResponse) VisitCreateAjusteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAjuste400ApplicationProblemPlusJSONResponse struct {
	externalRef0.BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateAjuste400ApplicationProblemPlusJSONResponse) VisitCreateAjusteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAjuste401ApplicationProblemPlusJSONResponse struct {
	externalRef0.UnauthorizedApplicationProblemPlusJSONResponse
}

func (response CreateAjuste401ApplicationProblemPlusJSONResponse) VisitCreateAjusteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAjuste403ApplicationProblemPlusJSONResponse struct {
	externalRef0.ForbiddenApplicationProblemPlusJSONResponse
}

func (response CreateAjuste403ApplicationProblemPlusJSONResponse) VisitCreateAjusteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAjuste404ApplicationProblemPlusJSONResponse externalRef0.Problem

func (response CreateAjuste404ApplicationProblemPlusJSONResponse) VisitCreateAjusteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAjuste413ApplicationProblemPlusJSONResponse struct {
	externalRef0.PayloadTooLargeApplicationProblemPlusJSONResponse
}

func (response CreateAjuste413ApplicationProblemPlusJSONResponse) VisitCreateAjusteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAjuste422ApplicationProblemPlusJSONResponse externalRef0.Problem

func (response CreateAjuste422ApplicationProblemPlusJSONResponse) VisitCreateAjusteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAjuste500ApplicationProblemPlusJSONResponse struct {
	externalRef0.InternalErrorApplicationProblemPlusJSONResponse
}

func (response CreateAjuste500ApplicationProblemPlusJSONResponse) VisitCreateAjusteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAjuste503ApplicationProblemPlusJSONResponse struct {
	externalRef0.ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response CreateAjuste503ApplicationProblemPlusJSONResponse) VisitCreateAjusteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMovimentacaoRequestObject struct {
	Params CreateMovimentacaoParams
	Body   *CreateMovimentacaoJSONRequestBody
}

type CreateMovimentacaoResponseObject interface {
	VisitCreateMovimentacaoResponse(w http.ResponseWriter) error
}

type CreateMovimentacao201JSONResponse Movimentacao

func (response CreateMovimentacao201JSONResponse) VisitCreateMovimentacaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMovimentacao400ApplicationProblemPlusJSONResponse struct {
	externalRef0.BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateMovimentacao400ApplicationProblemPlusJSONResponse) VisitCreateMovimentacaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMovimentacao401ApplicationProblemPlusJSONResponse struct {
	externalRef0.UnauthorizedApplicationProblemPlusJSONResponse
}

func (response CreateMovimentacao401ApplicationProblemPlusJSONResponse) VisitCreateMovimentacaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMovimentacao403ApplicationProblemPlusJSONResponse struct {
	externalRef0.ForbiddenApplicationProblemPlusJSONResponse
}

func (response CreateMovimentacao403ApplicationProblemPlusJSONResponse) VisitCreateMovimentacaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMovimentacao404ApplicationProblemPlusJSONResponse externalRef0.Problem

func (response CreateMovimentacao404ApplicationProblemPlusJSONResponse) VisitCreateMovimentacaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMovimentacao409ApplicationProblemPlusJSONResponse externalRef0.Problem

func (response CreateMovimentacao409ApplicationProblemPlusJSONResponse) VisitCreateMovimentacaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMovimentacao413ApplicationProblemPlusJSONResponse struct {
	externalRef0.PayloadTooLargeApplicationProblemPlusJSONResponse
}

func (response CreateMovimentacao413ApplicationProblemPlusJSONResponse) VisitCreateMovimentacaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMovimentacao422ApplicationProblemPlusJSONResponse externalRef0.Problem

func (response CreateMovimentacao422ApplicationProblemPlusJSONResponse) VisitCreateMovimentacaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMovimentacao500ApplicationProblemPlusJSONResponse struct {
	externalRef0.InternalErrorApplicationProblemPlusJSONResponse
}

func (response CreateMovimentacao500ApplicationProblemPlusJSONResponse) VisitCreateMovimentacaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMovimentacao503ApplicationProblemPlusJSONResponse struct {
	externalRef0.ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response CreateMovimentacao503ApplicationProblemPlusJSONResponse) VisitCreateMovimentacaoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ListProdutosRequestObject struct {
}

type ListProdutosResponseObject interface {
	VisitListProdutosResponse(w http.ResponseWriter) error
}

type ListProdutos200JSONResponse ProdutoList

func (response ListProdutos200JSONResponse) VisitListProdutosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProdutos401ApplicationProblemPlusJSONResponse struct {
	externalRef0.UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListProdutos401ApplicationProblemPlusJSONResponse) VisitListProdutosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListProdutos403ApplicationProblemPlusJSONResponse struct {
	externalRef0.ForbiddenApplicationProblemPlusJSONResponse
}

func (response ListProdutos403ApplicationProblemPlusJSONResponse) VisitListProdutosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListProdutos500ApplicationProblemPlusJSONResponse struct {
	externalRef0.InternalErrorApplicationProblemPlusJSONResponse
}

func (response ListProdutos500ApplicationProblemPlusJSONResponse) VisitListProdutosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListProdutos503ApplicationProblemPlusJSONResponse struct {
	externalRef0.ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response ListProdutos503ApplicationProblemPlusJSONResponse) VisitListProdutosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProdutoRequestObject struct {
	Params CreateProdutoParams
	Body   *CreateProdutoJSONRequestBody
}

type CreateProdutoResponseObject interface {
	VisitCreateProdutoResponse(w http.ResponseWriter) error
}

type CreateProduto201JSONResponse Produto

func (response CreateProduto201JSONResponse) VisitCreateProdutoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProduto400ApplicationProblemPlusJSONResponse struct {
	externalRef0.BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateProduto400ApplicationProblemPlusJSONResponse) VisitCreateProdutoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProduto401ApplicationProblemPlusJSONResponse struct {
	externalRef0.UnauthorizedApplicationProblemPlusJSONResponse
}

func (response CreateProduto401ApplicationProblemPlusJSONResponse) VisitCreateProdutoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProduto403ApplicationProblemPlusJSONResponse struct {
	externalRef0.ForbiddenApplicationProblemPlusJSONResponse
}

func (response CreateProduto403ApplicationProblemPlusJSONResponse) VisitCreateProdutoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProduto409ApplicationProblemPlusJSONResponse externalRef0.Problem

func (response CreateProduto409ApplicationProblemPlusJSONResponse) VisitCreateProdutoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProduto413ApplicationProblemPlusJSONResponse struct {
	externalRef0.PayloadTooLargeApplicationProblemPlusJSONResponse
}

func (response CreateProduto413ApplicationProblemPlusJSONResponse) VisitCreateProdutoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProduto422ApplicationProblemPlusJSONResponse struct {
	externalRef0.ValidationFailedApplicationProblemPlusJSONResponse
}

func (response CreateProduto422ApplicationProblemPlusJSONResponse) VisitCreateProdutoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProduto500ApplicationProblemPlusJSONResponse struct {
	externalRef0.InternalErrorApplicationProblemPlusJSONResponse
}

func (response CreateProduto500ApplicationProblemPlusJSONResponse) VisitCreateProdutoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProduto503ApplicationProblemPlusJSONResponse struct {
	externalRef0.ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response CreateProduto503ApplicationProblemPlusJSONResponse) VisitCreateProdutoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ListMovimentacoesRequestObject struct {
	Id ProdutoId `json:"id"`
}

type ListMovimentacoesResponseObject interface {
	VisitListMovimentacoesResponse(w http.ResponseWriter) error
}

type ListMovimentacoes200JSONResponse MovimentacaoList

func (response ListMovimentacoes200JSONResponse) VisitListMovimentacoesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListMovimentacoes401ApplicationProblemPlusJSONResponse struct {
	externalRef0.UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListMovimentacoes401ApplicationProblemPlusJSONResponse) VisitListMovimentacoesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListMovimentacoes403ApplicationProblemPlusJSONResponse struct {
	externalRef0.ForbiddenApplicationProblemPlusJSONResponse
}

func (response ListMovimentacoes403ApplicationProblemPlusJSONResponse) VisitListMovimentacoesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListMovimentacoes404ApplicationProblemPlusJSONResponse struct {
	externalRef0.NotFoundApplicationProblemPlusJSONResponse
}

func (response ListMovimentacoes404ApplicationProblemPlusJSONResponse) VisitListMovimentacoesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListMovimentacoes500ApplicationProblemPlusJSONResponse struct {
	externalRef0.InternalErrorApplicationProblemPlusJSONResponse
}

func (response ListMovimentacoes500ApplicationProblemPlusJSONResponse) VisitListMovimentacoesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListMovimentacoes503ApplicationProblemPlusJSONResponse struct {
	externalRef0.ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response ListMovimentacoes503ApplicationProblemPlusJSONResponse) VisitListMovimentacoesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetSaldoRequestObject struct {
	Id ProdutoId `json:"id"`
}

type GetSaldoResponseObject interface {
	VisitGetSaldoResponse(w http.ResponseWriter) error
}

type GetSaldo200JSONResponse Saldo

func (response GetSaldo200JSONResponse) VisitGetSaldoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSaldo401ApplicationProblemPlusJSONResponse struct {
	externalRef0.UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetSaldo401ApplicationProblemPlusJSONResponse) VisitGetSaldoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetSaldo403ApplicationProblemPlusJSONResponse struct {
	externalRef0.ForbiddenApplicationProblemPlusJSONResponse
}

func (response GetSaldo403ApplicationProblemPlusJSONResponse) VisitGetSaldoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetSaldo404ApplicationProblemPlusJSONResponse struct {
	externalRef0.NotFoundApplicationProblemPlusJSONResponse
}

func (response GetSaldo404ApplicationProblemPlusJSONResponse) VisitGetSaldoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetSaldo500ApplicationProblemPlusJSONResponse struct {
	externalRef0.InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetSaldo500ApplicationProblemPlusJSONResponse) VisitGetSaldoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetSaldo503ApplicationProblemPlusJSONResponse struct {
	externalRef0.ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response GetSaldo503ApplicationProblemPlusJSONResponse) VisitGetSaldoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CreateAjuste Registra um ajuste de estoque, com motivo obrigatório — pode levar o saldo a negativo.
	// (POST /api/v1/estoque/ajustes)
	CreateAjuste(ctx context.Context, request CreateAjusteRequestObject) (CreateAjusteResponseObject, error)
	// CreateMovimentacao Registra uma entrada, saída ou devolução de estoque (nunca ajuste — endpoint próprio).
	// (POST /api/v1/estoque/movimentacoes)
	CreateMovimentacao(ctx context.Context, request CreateMovimentacaoRequestObject) (CreateMovimentacaoResponseObject, error)
	// ListProdutos Lista todos os produtos (SKUs) de estoque (sem paginação).
	// (GET /api/v1/estoque/produtos)
	ListProdutos(ctx context.Context, request ListProdutosRequestObject) (ListProdutosResponseObject, error)
	// CreateProduto Cria um produto (SKU) de estoque.
	// (POST /api/v1/estoque/produtos)
	CreateProduto(ctx context.Context, request CreateProdutoRequestObject) (CreateProdutoResponseObject, error)
	// ListMovimentacoes Lista todas as movimentações do produto, na ordem em que ocorreram (todos os tipos, sem paginação).
	// (GET /api/v1/estoque/produtos/{id}/movimentacoes)
	ListMovimentacoes(ctx context.Context, request ListMovimentacoesRequestObject) (ListMovimentacoesResponseObject, error)
	// GetSaldo Consulta o saldo atual do produto (soma de todas as movimentações, zero e negativo incluídos).
	// (GET /api/v1/estoque/produtos/{id}/saldo)
	GetSaldo(ctx context.Context, request GetSaldoRequestObject) (GetSaldoResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// CreateAjuste operation middleware
func (sh *strictHandler) CreateAjuste(ctx *gin.Context, params CreateAjusteParams) {
	var request CreateAjusteRequestObject

	request.Params = params

	var body CreateAjusteJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAjuste(ctx, request.(CreateAjusteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAjuste")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateAjusteResponseObject); ok {
		if err := validResponse.VisitCreateAjusteResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateMovimentacao operation middleware
func (sh *strictHandler) CreateMovimentacao(ctx *gin.Context, params CreateMovimentacaoParams) {
	var request CreateMovimentacaoRequestObject

	request.Params = params

	var body CreateMovimentacaoJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateMovimentacao(ctx, request.(CreateMovimentacaoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateMovimentacao")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateMovimentacaoResponseObject); ok {
		if err := validResponse.VisitCreateMovimentacaoResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProdutos operation middleware
func (sh *strictHandler) ListProdutos(ctx *gin.Context) {
	var request ListProdutosRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListProdutos(ctx, request.(ListProdutosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProdutos")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListProdutosResponseObject); ok {
		if err := validResponse.VisitListProdutosResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProduto operation middleware
func (sh *strictHandler) CreateProduto(ctx *gin.Context, params CreateProdutoParams) {
	var request CreateProdutoRequestObject

	request.Params = params

	var body CreateProdutoJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProduto(ctx, request.(CreateProdutoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProduto")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateProdutoResponseObject); ok {
		if err := validResponse.VisitCreateProdutoResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMovimentacoes operation middleware
func (sh *strictHandler) ListMovimentacoes(ctx *gin.Context, id ProdutoId) {
	var request ListMovimentacoesRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListMovimentacoes(ctx, request.(ListMovimentacoesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMovimentacoes")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListMovimentacoesResponseObject); ok {
		if err := validResponse.VisitListMovimentacoesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSaldo operation middleware
func (sh *strictHandler) GetSaldo(ctx *gin.Context, id ProdutoId) {
	var request GetSaldoRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSaldo(ctx, request.(GetSaldoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSaldo")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetSaldoResponseObject); ok {
		if err := validResponse.VisitGetSaldoResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FtLbxzHEf4rjUkOJDLkLiU5gdfIgaaogLJEMnwIBkxhUZwuLlue6Rr2Y6EHCORH5A8IPhgOoJPgS67z",
	"T/JLgu6e585wuTJkkwl8Efcx3V1V/dVXr9W7KKEsJ4nS6GjyLspBQYYGlX93qIhbQ3vcvREymkQ5mMso",
	"jiRkGE0iwaM4UnhlhUIeTYyyGEc6ucQM3IoLUhmYaBJZ6580b3K3Shsl5Cy6vo7d4RnJ6Y5WFyf0PUq3",
	"iqNOlMiNIHeg/5iBNGJj5/joCePANGpd/EAxo3MlZmCKj0oQw4x5SbQofix+Rs2uLDJIDSrIGGoDnDaj",
	"OGhxicBRNXp86/feCCIs02hRg2v3sM5JavQGK/X5GvgRXlnUJnwoDUr/EvI8FQk43Ua5ovMUsz+90uT1",
	"bk75o8KLaBL9YdTczSh8q0flCYdhcRCha7EdUjk5OzXm+IGYdP8UPzGbsafHB/tsXrxPBSe2lhBHJuQc",
	"UsGnTpb1zai5mSekzgXn4WZ+Y0WOMWM5qkxU122ZhwAyUmKGmZM6aKHbIu9Jg0pCuqsUqTsQ253LhBei",
	"MW8QaYpOpo6B98k8ISv5HQh6hIlVuoQGSne6ghoSksz0wknWEfcQ3qQE/IToGagZ3hm8IREZME4sFZkw",
	"2BbxGNVcJHgqYQ4ihfP0LqR8jDlKXvxLJgKYkFw4kig+zDEtzauDlFPbiNkx9KkEay5JibfI78j3Sp4t",
	"qQLa0r1wbOEleAIivRMJdyDLSbc4oDTsvBZteuFli1lCGfOep52JrytC94y9oxAMbr+y2mCLs3NFOSoj",
	"Aq1nZMSc/Ct4/QzlzFxGky/G4zjKhKzeb/UCXOy2cQF0KvgK8TCOrqwLdBw49gPhY0wNMNBaSOAUM2ll",
	"AuwtKmL/+cc/WV6CikmcgZM2ZkImqdVijizFOUhOjJiGlBOD+ikXEmuxhDR/ftTI5VhrhioKUa4Kid+1",
	"leqIHFd2ellvQeevMDFOtWDn5zQXGUoDCdASazcPTTmWxuta46Ad+p0MnJgROf318e6Lg2enO9sHbC0g",
	"gROTxBLQxDgyq2vTwZUV3nQc55Rad1gZBqHaEaxGaZxjxrdfXghKtwH7wD/VtsNnxskxZrlCF+fd/QlF",
	"LCct3L14ZYk5AKUuFUggTWzqDFTGJycRMmA5KCOUM5cz6UoQiSP3aF+afW/q7aenxye7jcWtRjaCXIzm",
	"WyPUhq4sjsC7oHanobSZA9ru/snR9uPtKI6Ot/f83/p2WxhrpZNtlHp54iVgLe/rZrCW2e+NOE2Ii9ki",
	"K2ytwAqSMlxY9mCFZVZ60acZcsGht8Et6xfMUwpfCtPbfMgqHdD2raEEcJoGD6jxwsHghhH+iJ5CK6K9",
	"Yd8utg4VokwuXRari48dFgiAc1iSNi1zgJDLD+x+O9ssOalG5BBH3Hr4PeGMp8X7OrKwHFNg4AN4KB3W",
	"agIh2wovTQBa906tyWVkQqEBF3Hz4mesAs6KFFKWUjDHdFWtKtZZZr4TkVPXeAu+4LfuEEVJHkN8UeNx",
	"EDo9JeKWY9zmVM/EEM0Ig1n3xTJlF1FSHghKwZu+4n7HIbEGIDd5VxPzi919T8c7B88Pj9yL3Re7+ycH",
	"URzt7btX20d77k3wwunz7f3T7WcDjB1XDYZl3Npb8+sRTcXLKzDvcnIN976cYW8DRmmaz4GJysq/HA7H",
	"zov7Yujq409NIcPCoZN6ztpP/Tzx+mQuA1b7YOCqV8V7pnAmtCtlwfOST4NFmYPEvi3kSDy5xFmZBIJR",
	"MC9+0m7PX5SWhL1vyU+anorAlNfdiR7uPQTxNWS5CxyN2QY2vHA7dR8HzhVqvflW5NFtOUBYHodDhy5j",
	"oQrrXYVvdUhi4fqJ3VT3sbWjJzvsy0df/MWn0sMqL5R3xUfnPgy1Kd67spmTr+Fil50CI5akwqerRoEB",
	"5e+nNgJmINKpgdDO65mNowGRDnp6KBOHNdUsJ8USV3fGLFfoa4PQd9Q5aQMeQKGC8Gj0/cZVHLQPjJ6r",
	"hptDbQYTlD2O0ogLkQAntdj7i5mYWUgZuDLoHIsfIb0k9u1Gmdhu7PHNIStpA8bqDroejb8cTv1NuoDa",
	"HZIXqUjMYMz2H3RAe07WTM5TkN/fClr/bXVmLWV9qSWaO+bqQ9uph4lVwrw5dnfQ6d5q1FqQ3CH6Xgwh",
	"03/OfLkdGiSYCSNCnZnSTMi6z5yELeo+s3lVbd6oCbn4Bv0F984dhExX7NGgzL5dIuQFDUkvncd4/kwo",
	"s7JO8ziykvQmrEyGNFs7/uaUZcUHKTJajzts+zPqM7mGvmkIMdNQfHB/QzXtt1yPWUmfzB0mtU0NeMP5",
	"pJA9dpLhHM9kApmQl6RjhvrKOp9gzrwzq0AWP8JXoUeZkDTFT87fZio4m8RZ8TERFGjd4T87k5K0r/d1",
	"WfC3NBtBnrO18dbG+OH65pk8kyfknIUMMHwtZs2VroWrY82NrX/FYGioEBZmZ9JAdu6kW/CyZrKwyfZR",
	"Xrqg5Q9spHLFeF78+9xxp5fqEGZCQum8FyI1inzXm6NsLisV2sAMpQ56OxL2HVHUCfn4qA2cyTmqoFCG",
	"2uXnmAgdNkjFOfogyZE92dvfeLwxfrC1PmEu4zis7h/PpHvfRGRCHa547juEvtcAQZay4eBUqB10Ep08",
	"ZYcpGBci2AbLio/cplRpHsWREzBAc2tzvDn2VVGOEnIRTaKHm+PNhy5igLn0LnpDePaBlEKm5GKLD0F7",
	"3OG91d/zGzXzre+GPax5ZNQbT12/rInla+JvlrQ9P63dOdSFvO4yn6sgF8dND8Zbn02EhQqp128NwjXJ",
	"Ffl+8KPx+KaNa0lH/amYX7m18spOM9yvfbjy2maC5Rc+uoNWdelNNwxaqsJTAk2bL8Mw4NHW6ooujmbc",
	"8gcP7kDdv9dVc92dB0aWhbq5aqqytaa6rhuvcfnQtBztkhKlJb74BKB1J4B+8epmHBgf+XTBZhmoN35s",
	"FjyA2awMby0qD8OGUtPOfLpu0qc4B3VDK97AzBFTVNHaS3f0IudlbTK+jfk6bn3P+W9oOnDPWPB5t9xs",
	"Ss3f2fA3YMPxl3cxCvWJLVsj285tvc+H3HfdFYAutVUCXDkYHLty62re6z6cCqnthUhEOVX6f2P4tn2a",
	"L4aJvj91u8dED2yhzmEDaCiT+bVyvBhCg6N9lDwnIQ3LVfExDyGt4founQ8yflWOOd1mOMD17Zw96tHj",
	"+LPRY7spOYCLE+KkGem6fty8M267PzB65msjs2gaX1rr9Q5yNGYsb2q/DkxqDLy8jpdG/Krbe8+D/cJ0",
	"9TeO83VL/Ob4FNrz/5tx/S7iZNWxfVW8Z9aIVLz100RSjKxRVAG/jIdhOjLl1gv2eeudlZb3fsJ0r0hj",
	"x+USNmuMdvzNaZsrbmCGJbFj9E7w637tcGM46bR8PplMml8OBxb5leJRb3o6HJRAM9CLzUvGa0xu3nUK",
	"vtLC+qei9zO83WbkmEnwPczMJcku3lFCSvlW6lodHo3IScdsWST8hIQpgL4eUw6C/W9ownjznmI8CDdY",
	"mPgGgrGQ/o7lz8O61Yyi7s4sGJethV+54I2Aj8NPMrGp//z8ufjASXdQXI7Ar9uzKI+6hTHQdy8dujSq",
	"eQVLq9JoEo086srd3g3nMN35TSt8hF/suAwnlC/1NCGrfteDvPyPA2QZvk5Sq8uBZjnKqoPOddyblS6U",
	"SnhDpdTarevS/S23+302V13ObVrOURLIkYE1DsbA4aYuXOvIqsXWP2xncVLlk5javeodwg1ev7z+bwAA",
	"AP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "common.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
