// Package apicommon provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apicommon

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/antoniobt12062002/torcida-jovem-platform/api/internal/platform/money"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// Cents Valor monetário em centavos de real (10000 equivale a R$ 100,00).
//
// Example: 12345
type Cents = money.Cents

// Cursor Cursor opaco de paginação, devolvido em next_cursor.
type Cursor = string

// FieldError defines model for FieldError.
type FieldError struct {
	// Code Example: required
	Code string `json:"code"`

	// Field Example: address.zip
	Field string `json:"field"`
}

// Problem Erro no formato application/problem+json (RFC 9457).
type Problem struct {
	// Code Código estável do erro, para o cliente tratar.
	//
	// Example: email_taken
	Code   string `json:"code"`
	Detail string `json:"detail"`

	// Errors Erros por campo, presente em respostas de validação.
	Errors *[]FieldError `json:"errors,omitempty"`

	// RequestId Identificador da requisição, igual ao cabeçalho X-Request-Id.
	RequestId string `json:"request_id"`

	// Status Example: 409
	Status int `json:"status"`

	// Title Example: Conflict
	Title string `json:"title"`

	// Type Example: about:blank
	Type string `json:"type"`
}

// CsrfToken defines model for CsrfToken.
type CsrfToken = string

// CursorParam Cursor opaco de paginação, devolvido em next_cursor.
type CursorParam = Cursor

// Limit defines model for Limit.
type Limit = int

// BadRequest Erro no formato application/problem+json (RFC 9457).
type BadRequest = Problem

// Conflict Erro no formato application/problem+json (RFC 9457).
type Conflict = Problem

// Forbidden Erro no formato application/problem+json (RFC 9457).
type Forbidden = Problem

// InternalError Erro no formato application/problem+json (RFC 9457).
type InternalError = Problem

// NotFound Erro no formato application/problem+json (RFC 9457).
type NotFound = Problem

// PayloadTooLarge Erro no formato application/problem+json (RFC 9457).
type PayloadTooLarge = Problem

// ServiceUnavailable Erro no formato application/problem+json (RFC 9457).
type ServiceUnavailable = Problem

// TooManyRequests Erro no formato application/problem+json (RFC 9457).
type TooManyRequests = Problem

// Unauthorized Erro no formato application/problem+json (RFC 9457).
type Unauthorized = Problem

// ValidationFailed Erro no formato application/problem+json (RFC 9457).
type ValidationFailed = Problem

// ServerInterface represents all server handlers.
type ServerInterface interface {
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {

}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ConflictApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type InternalErrorApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type PayloadTooLargeApplicationProblemPlusJSONResponse Problem

type ServiceUnavailableApplicationProblemPlusJSONResponse Problem

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int
}
type TooManyRequestsApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type ValidationFailedApplicationProblemPlusJSONResponse Problem

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFdRbxvHEf4ri20ebPRInmQ5htinVo0Ap2nqSkpgIA6I4e2QGnt357S7R0g2+GOMPAQukCehv+D+WDF7",
	"R4oU6bh54QvB27ud+Xbmm5lvP+iKXc0efYp6/EFfIxgM+e/rC7xpMKaXRp4MxipQnYi9HuuXBn2iGVVg",
	"OCgDKuBNQ5HaX9tfeKgLHatrdCAb012NeqxjCuTnerlcFrqGAA5T7+cshtkVv0O/6yYvK/CJBmeXF+fi",
	"KGKM7S9cKJ4GmkNq7wOxQreB4L8Y1U2DCmzCAE5hTGAyKhKj3RF1oT04QfY62x50EAqd7QQ0epxCg793",
	"kkKfNSFyeCXH2QXfvRTMdftxTh4KtSBvWBlUHm/TpMofrHHdNBjuHmB1b7dC+VXAmR7rP40ecjbq3sZR",
	"5y2j+o4cpV08/24kkAYMCgJK6KOqOazQfQ6HzdY2YRicQWOTHj8vC+3gllzj9PiolCfy/VOxChf5hHMM",
	"XeYDxpp9xJz4v4HpKSZPFfuEPv+FurZUgeAe1YGnFt2f30bOBPn/ovGq29U5fZQWDjU/pqzy8tN+Uo1T",
	"317+63u1aD9aMqyeVCzB8guwZCYC4ulQS+bZzyxVB0YuPhOrip3intYKUgNWPZFM4i262ko1ANlJAike",
	"bpSFmCZgHPXYzzlMyZiu4A4F/hKdqjE4WpVvo3JJo+JAc3QS4y7mMYN86RMGD/abEDgcEqg4VJS9P6S/",
	"wzJBAdMF8XtO59x4c0hoF5ibQkdW9OI2wJqkntNkJpA6gK/gzjKYK+bvIMzx8CUGFTlQhlXuIJhBXWJY",
	"UIU/eFgAWZjag+L6O9boTfsfXxEo8oakGbW/LdD2IYwdvEnzgK8L5hXzP8Hf9e0qHhL0FfoEiRYQZcrh",
	"bYUx8l8Uqwqm2P4K9prVBaZwN/jrLGFQht7LhzfS7TmqiPPGG45KwELIw4cXeRpuzPoNA7uD43JlAlL7",
	"SYGqQ3t/K7lNK2jbE//3h8Cy0D94aNI1B3qP5tA9qNcPfYOHnN0fpblnn+dA9rCYzsDVHDe6X0/FxRrT",
	"ZJZBFbnt5w4UhZTLVcg7EbUScNvWfwTLQTn2mNqPvVCqJGsLjkKFgDI7jsqyLJWMwwVYVKAuvlIyzsvy",
	"qWQWb8HVUqlHx89Onhd6xsFB6rL69Yne0ACnZfni6PT0+PnJi5Py9PRoQxAMdt894kahbwdzHvSrgvlu",
	"2B1r482AXM0hp6WGdK3Hek7pupkOK3YjYbwnnqaj4/Lr47I8HiUOFRkYvOUFukFtIQn4EdQ0WjX10Xo1",
	"u9zQdZ+VdFxDlWVcDaKcsoIolMEF24WIBnSPBd4j6Vjoc0Jr1rOtDlxjSIR9ZzG5La7j/qBJ91iaiaXt",
	"z8GYgDEO31O9u2O5KXF/6rcXndOf11/z9C1WKc+Rnrs7wciD0rPq6MDqc2Winlycn6nTk+cvMpv2n/VR",
	"nNt7Q/MscdqP0p4lqCFwoeTqIL3PEvqEKgVIELZIqjfUz754GUxAdo+eL3RXXPtP2mnlSqq1UHXAmP3n",
	"e0esOSbI9dRV7foWRAld/FJz2KDCco0XQoA73ecKY5rQH72FFYrmogxha1K8HvQzbPDS7CVmTJCauMWn",
	"k/J0t5EXOlGyj3i6VsV7DHcLWzSdcpPGUwv+3Rdpmt+ufK5RrrPZ83crXLtkluOJhKJ0dynB7ygoE4HY",
	"nzG/o31czOsqq4NudKCjJGXuWVmek1/fnKrOxPrqlN5OeuMP54Oa/pG7zFI2zXifw54imClVsWs8VR2p",
	"VMAmkaX3IJOiRstRdTJQZr2sufbeNJbjG/9k1dgKRZko6U7UdlSzJjWB49Oh+iYmVIarxqFPva7MYHCB",
	"KrCQGvPqmyw2209C93nouO5x3t5XxGOFFqISGjrlIapYY5U3bsCRDYZd+5snHr7x61SO9dW36lUPVA1U",
	"tXF4+Q8hkb2W0+pCLzDELkZHw3JYCqu4Rg816bF+NiyHz6S/QLqWvOZkh0UWOD990E2weqxHevnz8n8B",
	"AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
